#ifndef WAZERO_CORE_H
#define WAZERO_CORE_H

#include <string>
#include <vector>
#include <cstdint>
#include "libwazerocore.h" // Generated by Go build

class WazeroCore {
public:
    // Initializes the Go runtime. Throws std::runtime_error on failure.
    WazeroCore();
    
    // Destroys the Go runtime and releases resources.
    ~WazeroCore();

    // Non-copyable to prevent double-freeing the Go handle.
    WazeroCore(const WazeroCore&) = delete;
    WazeroCore& operator=(const WazeroCore&) = delete;

    // Loads a Wasm binary module. Returns true on success.
    bool loadModule(const uint8_t* data, size_t size);

    // FAST PATH: Invokes a function with numeric arguments (e.g., malloc).
    uint64_t callNumeric(const std::string& funcName, const std::vector<uint64_t>& args);

    // RICH PATH: Invokes the guest router using JSON strings.
    std::string callGuest(const std::string& service, const std::string& method, const std::string& jsonArgs);

private:
    GoUintptr goHandle;
};

#endif // WAZERO_CORE_H